// GIVEN a command-line application that accepts user input
// WHEN I am prompted for information about my application repository
// THEN a quality, professional README.md is generated with the title of your project and sections entitled Description, Table of Contents, Installation, Usage, License, Contributing, Tests, and Questions
// WHEN I enter my project title
// THEN this is displayed as the title of the README
// WHEN I enter a description, installation instructions, usage information, contribution guidelines, and test instructions
// THEN this information is added to the sections of the README entitled Description, Installation, Usage, Contributing, and Tests
// WHEN I choose a license for my application from a list of options
// THEN a badge for that license is added hear the top of the README and a notice is added to the section of the README entitled License that explains which license the application is covered under
// WHEN I enter my GitHub username
// THEN this is added to the section of the README entitled Questions, with a link to my GitHub profile
// WHEN I enter my email address
// THEN this is added to the section of the README entitled Questions, with instructions on how to reach me with additional questions
// WHEN I click on the links in the Table of Contents
// THEN I am taken to the corresponding section of the README
// ```

//Dependencies
  //inquirer
  //generateMarkdown

//Functions
 //arrray with questions 
 // inq to ask:
 //1. the title of your project(please enter git-hub username)
 //2.  Description,
 //3. Table of Contents(autogenerated)-#id +anchor tags
 //4. Installation requerement
 //5.Usage
 //6.License(choices)
 //7.Contributing
 //8.Tests
 //9.Questions
 //each question accepts an input as an answer or give a user a list of choices
 //and  it uses fs.appendFile(writeFile) to create a md.file with all info about README

//User Input

// array of questions for user
const questions = [

];

// function to write README file
function writeToFile(fileName, data) {
}

// function to initialize program
function init() {

}

// function call to initialize program
init();
